import { Poppins, Inter, Rubik_Puddles } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
const poppins = Poppins({ weight: "900", subsets: ["latin"] });
const rubik = Rubik_Puddles({ weight: "400", subsets: ["cyrillic"] });

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
